Repository DeveloperAcademy-POSTECH/MC3-Team15-DaeguGoodPriceShop, pull requests merged in 2022-07, with the labels that each got.

#15 Feature/json data
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/Shop.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Resource/DaeguGoodPriceShop.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Feature

#18 [Feature] #6 : Design Map view UI
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Main.storyboard
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
Labels: Feature

#27 [Bug] #23 : Fix wrong json data and entity
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/Shop.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Resource/DaeguGoodPriceShop.json
Labels: Bug

#26 [Feature] User Location, Annotation
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Info.plist
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/Shop.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Manager/LocationManager.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Resource/DaeguGoodPriceShop.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController+.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Feature

#33 [Refactor] #31 : Refactor shop entity
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/Shop.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift
Labels: Refactor

#34 [Refactor] #32 : Refactor Model, ViewModel, View
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController+.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ShopAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Refactor

#35 [Feature] #28 : Annotation View UI
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/bakery.imageset/Bread_Green.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/bakery.imageset/Bread_Green@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/bakery.imageset/Bread_Green@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/bakery.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/bath.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/bath.imageset/image 24.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/bath.imageset/image 24@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/bath.imageset/image 24@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cafe.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cafe.imageset/_cafe.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cafe.imageset/_cafe@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cafe.imageset/_cafe@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/chineseFood.imageset/Chinese_Mien 22222324 1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/chineseFood.imageset/Chinese_Mien 22222324 1@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/chineseFood.imageset/Chinese_Mien 22222324 1@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/chineseFood.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cleaning.imageset/Cleaning 1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cleaning.imageset/Cleaning 1@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cleaning.imageset/Cleaning 1@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cleaning.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki 1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki 1@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki 1@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/hairCut.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/hairCut.imageset/Scissors 1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/hairCut.imageset/Scissors 1@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/hairCut.imageset/Scissors 1@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/japaneseFood.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/japaneseFood.imageset/Japanese_Sushi_Green.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/japaneseFood.imageset/Japanese_Sushi_Green@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/japaneseFood.imageset/Japanese_Sushi_Green@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/koreanFood.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/koreanFood.imageset/spoon and sticks 1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/koreanFood.imageset/spoon and sticks 1@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/koreanFood.imageset/spoon and sticks 1@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/skinCare.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/skinCare.imageset/Skin 1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/skinCare.imageset/Skin 1@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/skinCare.imageset/Skin 1@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/westernFood.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/westernFood.imageset/yangsik 1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/westernFood.imageset/yangsik 1@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/westernFood.imageset/yangsik 1@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/BakeryAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/BathAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/CafeAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ChineseFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/CleaningAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/FlourBasedFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/HairCutAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/JapaneseFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/KoreanFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ShopAnnotatable.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ShopAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/SkinCareAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/WesternFoodAnnotationView.swift
Labels: Feature

#38 [Feature] #29, #30 : Clustering
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/CateringStore.colorset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/HairdressingShop.colorset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/LaundryShop.colorset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/ServiceShop.colorset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/BakeryAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/BathAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/CafeAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ChineseFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/CleaningAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ClusteringAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/FlourBasedFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/HairCutAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/JapaneseFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/KoreanFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/SkinCareAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/WesternFoodAnnotationView.swift
Labels: Feature

#37 [Refactor] #36 : Implement MapView UI
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
Labels: Refactor

#40 [Refactor] #39 : Refactor after code review
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/BakeryAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/BathAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/CafeAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ChineseFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/CleaningAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/FlourBasedFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/HairCutAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/JapaneseFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/KoreanFoodAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ShopAnnotatable.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/SkinCareAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/WesternFoodAnnotationView.swift
Labels: Refactor

#46 [Bug] #44 : Fix icon background
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki 1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki 1@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki 1@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki@1x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki@3x.png
Labels: Bug

#48 [Feature] #43 : Add favorite shop logic
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Feature

#53 [Feature] #50, #52 : Create Half Modal for categorizing view and detail view.
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ModalHeight.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/HalfModalView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DefaultModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalViewController.swift
Labels: Feature

#63 [Feature] #59 : Add Information in Half-Modal
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/DataItem.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DefaultModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/Shared/HeaderView.swift
Labels: Feature

#68 [Feature] #61 : 즐겨찾기 가게 리스트 구현
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/DataItem.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DefaultModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
Labels: Feature

#69 [Feature] #62 : 일반 가게 리스트 구현
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DefaultModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift
Labels: Feature

#65 [Feature] #58 : Create annotation press action and favorite button.
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Feature

#71 [Feature] #70 : Category View UI
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/test.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/test.imageset/Rectangle 24.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
Labels: Feature

#80 [Feature] #77, #78, #79 : Filtering category with selectable list cells
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ModalHeight.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/DataItem.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
Labels: Feature

#76 [Feature] #75, #73 : DetailModalView 구현
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Feature

#81 [Feature] #74 : CellView CallButton 전화 기능 구현
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
Labels: Feature

#84 [Refactor] #82 : Refactor zoom
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ModalHeight.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
Labels: Refactor

#86 [Refactor] #85 : Category View UI
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/UIFont+Extension.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
Labels: Refactor

#92 [Feature] #90, #91 : CategoryView favorite logic
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Feature

#95 [Bug] #93 : Fix favorite bug
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Bug

#88 [Refactor] #83 : Change annotation update method
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/AnnotationView/ShopAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Refactor

#89 [Refactor] #87 : Refactor Detail Modal
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Refactor

#99 [Refactor] #94 : Diffable Datasource ItemIdentifierType 분기 처리
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/DataItem.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/StoreListItem.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
Labels: Refactor

#100 [Feature] #96 : Unfiltering
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
Labels: Feature

#105 [Refactor] #97 : Change Modal Height
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ModalHeight.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
Labels: Refactor

#112 [Refactor] #111 : Change flourbasedFood icon
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki 6@1x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki 6@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki 6@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki@1x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki@2x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/flourBasedFood.imageset/toppoki@3x.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Refactor

#113 [Bug] #101 : Fix func_resizedImage
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/AnnotationView/ShopAnnotationView.swift
Labels: Bug

#115 [Refactor] #114 : replace UITextView with UILabel
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Refactor

#117 [Bug] #116 : Change app name english to korean
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/ko.lproj/InfoPlist.strings
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/ko.lproj/LaunchScreen.strings
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/ko.lproj/Main.strings
Labels: Bug

#119 [Bug] #118 : Annotation deselection
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
Labels: Bug

#123 [Bug] #122 : Portrait fix
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/AppDelegate.swift
Labels: Bug

#125 [Bug] #124 : Unfiltering
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
Labels: Bug

#132 [Bug] #131 : Fix category modal view pan gesture view height
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
Labels: Bug

#130 [Bug] #129 : Fix annotation filtering flashing
  DaeguGoodPriceShop/DaeguGoodPriceShop/Entity/ShopCategory.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Bug

#134 [Bug] #127 : Fix bugs that do not apply changes when clicking a button
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Bug

#135 [Bug] #128 : Implement favourite button UI in detail modal
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Bug

#137 [Bug] #133 : Change drag gesture area
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalViewController.swift
Labels: Bug

#146 [Bug] HOTFIX : Change modal view layout
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
Labels: Bug

#141 [Bug] #140 : Change Annotation Update Method
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Bug

#144 [Bug] #143 : Syncronize map and modal
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Bug

#145 [Bug] #142 : Fix layout and adjust stack heights
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Bug

#147 [Bug] HOTFIX : Resolve conflict
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Bug

#149 [Bug] #148 : Adjust Detail Modal View subTitleAddressView layout
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Bug

#139 [Bug] #138 : Fix Category Images
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cateringCategory.imageset/CateringShop-1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cateringCategory.imageset/CateringShop-2.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cateringCategory.imageset/CateringShop.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/cateringCategory.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/hairCategory.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/hairCategory.imageset/Hair-1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/hairCategory.imageset/Hair-2.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/hairCategory.imageset/Hair.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/laundryCategory.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/laundryCategory.imageset/laundry-1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/laundryCategory.imageset/laundry-2.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/laundryCategory.imageset/laundry.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/serviceCategory.imageset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/serviceCategory.imageset/service-1.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/serviceCategory.imageset/service-2.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/serviceCategory.imageset/service.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/test.imageset/Rectangle 24.png
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
Labels: Bug

#151 [Bug] #150 : Fix store favorite list
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Bug

#152 [Bug] HOTFIX : Fix unfiltering unavailable
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
Labels: Bug

#157 [Feature] #156 : Go to GoodShop Web URL
  DaeguGoodPriceShop/DaeguGoodPriceShop/Resource/DaeguGoodPriceShop.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
Labels: Feature

#163 [Bug]Adjust UI Components
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
Labels: Bug

#164 [Refactor] #159 : Data async fetching
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Refactor

#165 [Refactor] #160 : Divide MapViewModel to two
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/LocationManager.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapLocationViewModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapShopViewModel.swift
Labels: Refactor

#166 [Refactor] #162 : Data binding from combine to closure
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapLocationViewModel.swift
Labels: Refactor

#168 [Refactor] #161 : Change button background color
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/MainColor.colorset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/SubColorRed.colorset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
Labels: Refactor

#170 [Refactor] #169 : Change Subcategory button
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
Labels: Refactor

#179 [Refactor] #171 : Refactor JSON async logic
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
Labels: Refactor

#176 [Feature] #173 : Zoom to Cluster
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/AnnotationView/ClusteringAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapShopViewModel.swift
Labels: Feature

#180 [Refactor] #177, #178 : Data binding, Business logic
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/StoreListItem.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/DetailModalViewModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapShopViewModel.swift
Labels: Refactor

#187 [Refactor] #181 : Change UI DetailView & StoreList CellView & CategoryView
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/SubColorRed.colorset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/BasePaddingLabel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
Labels: Refactor

#185 [Refactor] #183 : Subcategory button change when selected
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapShopViewModel.swift
Labels: Refactor

#186 [Bug] #184 : Sync CategoryButton and StoreListModalView
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapShopViewModel.swift
Labels: Bug
