Repository DeveloperAcademy-POSTECH/MC3-Team15-DaeguGoodPriceShop, pull requests merged in 2022-08, with the labels that each got.

#182 [Refactor] #167 : Shop Distance Calculation
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/LocationManager.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
Labels: Feature

#189 [Project] #188 : 1.1 출시
  DaeguGoodPriceShop/DaeguGoodPriceShop.xcodeproj/project.pbxproj
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/MainColor.colorset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Assets.xcassets/SubColorRed.colorset/Contents.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/Application/Base.lproj/Main.storyboard
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/BasePaddingLabel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/LocationManager.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/MapModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/ShopAnnotation.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Model/StoreListItem.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/Resource/DaeguGoodPriceShop.json
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/AnnotationView/ClusteringAnnotationView.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/CategoryModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/DetailModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/DetailCategoryViewCell.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/ModalCollectionViewCell/StoreListViewCell.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/ModalViewController/StoreListModalViewController.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/DetailModalViewModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapLocationViewModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapShopViewModel.swift
  DaeguGoodPriceShop/DaeguGoodPriceShop/ViewModel/MapViewModel.swift
Labels: Project

#191 [Documentation] #190 : Update README.md
  README.md
Labels: Documentation

#193 [Bug] #192 : Fix selected annotation clustering
  DaeguGoodPriceShop/DaeguGoodPriceShop/View/MapViewController.swift
Labels: Bug

#195 [Documentation] #194 : Update README.md
  README.md
Labels: Documentation
